# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test
  	pod 'Firebase/Auth'
	pod 'GoogleSignIn'
	pod 'Validator', '~> 3.2'
	pod 'Firebase/Database'
	pod 'FirebaseCore'
	pod 'Firebase/Firestore'
	pod  'Firebase/Messaging'
	pod 'Firebase/Analytics'
	pod 'Firebase'
	pod 'HGCircularSlider', '~> 2.0.0'
	pod 'RealmSwift'
	pod 'FLAnimatedImage', '~> 1.0'
	pod "TinyConstraints"
	pod 'Charts'
	pod 'SCLAlertView'
	pod 'IQKeyboardManagerSwift'
	pod 'Purchases', '3.10.1'
	pod 'AppsFlyerFramework'
  target 'TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestUITests' do
    # Pods for testing
  end

end
